sudo: false

language: python
python:
  - "2.7"

script:
  - docker-compose run --rm web bin/wait-for-deps.sh coverage run --source=nuntium,contactos,mailit,instance manage.py test nuntium contactos mailit instance

after_script:
  # Log DB output in case issues occurred where this can help us debug quicly
  - docker-compose logs db elasticsearch

  # Upload code coverage data to codecov.io
  - "docker-compose run --rm `bash <(curl -s https://codecov.io/env)` web codecov"
