# Build on Travis's container-based infrastructure, which starts builds
# much faster:
sudo: false

language: python
python:
  - "2.7"
# command to install dependencies
services:
  - elasticsearch
  - rabbitmq
install:
  - pip install -r requirements.txt
  - pip install psycopg2
  - pip install -r requirements_testing.txt
# command to run tests
before_script:
  - psql -c 'create database writeit;' -U postgres
script:
  - coverage run --source=nuntium,contactos,mailit,instance manage.py test nuntium contactos mailit instance
  - coverage report -m
after_script:
  - coveralls --verbose
env:
  - DB=postgres
  - DB=sqlite3

